<?php

/**
 * @file
 * Lets you "ingest" any remotely-hosted media and display it via its embed code.
 */

/**
 * Implements hook_permission().
 */
function islandora_remote_media_permission() {
  $permissions = array(
    'ISLANDORA_REMOTE_MEDIA_EDIT_OBJ' => array(
      'title' => t('Edit Remote Media embed code'),
      'description' => t('Edit the OBJ datastream for Remote Media objects.'),
      'restrict access' => TRUE,
    ),
    'ISLANDORA_REMOTE_MEDIA_REPLACE_OBJ' => array(
      'title' => t('Replace Remote Media OBJ datastream'),
      'description' => t('Upload a file to replace the Remote Media OBJ datastream.'),
      'restrict access' => TRUE,
    ),
  );
  return $permissions;
}

/**
 * Implements hook_menu().
 */
function islandora_remote_media_menu() {
  $items = array();
  $items['islandora/object/%islandora_object/datastreams/remote_media/OBJ/edit'] = array(
    'title' => 'Edit Remote Media Embed Code',
    'file' => 'includes/remote_media_edit.form.inc',
    'page callback' => 'islandora_remote_media_edit_obj',
    'page arguments' => array(2),
    'access callback' => 'islandora_object_manage_access_callback',
    'access arguments' => array(
      array(
        'ISLANDORA_REMOTE_MEDIA_EDIT_OBJ',
      ), 2),
    'type' => MENU_CALLBACK,
  );
  return $items;
}


/**
 * Implements hook_CMODEL_PID_islandora_datastream_access().
 */
function islandora_remote_media_islandora_sp_remoteMediaCModel_islandora_datastream_access($op, AbstractDatastream $datastream, $user) {
  if ($op == ISLANDORA_REPLACE_DATASTREAM_CONTENT) {
    if ($datastream == 'OBJ') {
      $owner = $object->parent->owner;
      return ($user->name == $owner || user_access('ISLANDORA_REMOTE_MEDIA_REPLACE_OBJ'));
    }
  }
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_remote_media_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_remote_media');
  // Remote Media Content Model.
  $remote_media_content_model = $connection->repository->constructObject('islandora:sp_remoteMediaCModel');
  $remote_media_content_model->owner = 'fedoraAdmin';
  $remote_media_content_model->label = 'Islandora Remote Media Content Model';
  $remote_media_content_model->models = 'fedora-system:ContentModel-3.0';
  // ISLANDORACM Datastream.
  $datastream = $remote_media_content_model->constructDatastream('ISLANDORACM', 'X');
  $datastream->label = 'Islandora content model';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_remote_media_cmodel.xml", FALSE);
  $remote_media_content_model->ingestDatastream($datastream);
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $remote_media_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_remote_media_ds_composite_model.xml", FALSE);
  $remote_media_content_model->ingestDatastream($datastream);
  // Remote Media Collection.
  $remote_media_collection = $connection->repository->constructObject('islandora:remote_media_collection');
  $remote_media_collection->owner = 'fedoraAdmin';
  $remote_media_collection->label = 'Remote Media Collection';
  $remote_media_collection->models = 'islandora:collectionCModel';
  $remote_media_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $remote_media_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_remote_media_collection_policy.xml", FALSE);
  $remote_media_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $remote_media_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $remote_media_collection->ingestDatastream($datastream);
  return array(
    'islandora_remote_media' => array(
      'title' => 'Islandora Remote Media',
      'objects' => array(
        $remote_media_content_model,
        $remote_media_collection,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_remote_media_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_remote_media');
  return array(
    'Islandora Remote Media Object MODS form' => array(
      'form_file' => "$module_path/xml/islandora_remote_media_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_form_associations().
 */
function islandora_remote_media_islandora_xml_form_builder_form_associations() {
  return array(
    'islandora_remote_media_mods_form' => array(
      'content_model' => 'islandora:sp_remoteMediaCModel',
      'form_name' => 'Islandora Remote Media Object MODS form',
      'dsid' => 'MODS',
      'title_field' => array(
        'titleInfo', 'title',
      ),
      'transform' => 'mods_to_dc.xsl',
      'self_transform' => 'cleanup_mods.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_remote_media_islandora_sp_remoteMediaCModel_islandora_ingest_steps() {
  return array(
    'islandora_remote_media_upload' => array(
      'weight' => 5,
      'type' => 'form',
      'form_id' => 'islandora_remote_media_upload_form',
      'module' => 'islandora_remote_media',
      'file' => 'includes/remote_media_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_islandora_edit_datastream_registry().
 */
function islandora_remote_media_islandora_edit_datastream_registry($object, $dsid) {
  if (in_array('islandora:sp_remoteMediaCModel', $object->models) &&
    $dsid->id == 'OBJ') {
    return array(
      array(
        'name' => t('Media Embed Code Edit Form'),
        'url' => "islandora/object/{$object->id}/datastreams/remote_media/OBJ/edit",
      ),
    );
  }
}

/**
 * Implements hook_theme().
 */
function islandora_remote_media_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_remote_media' => array(
      'template' => 'theme/islandora-remote-media',
      'file' => 'theme/theme.inc',
      'pattern' => 'islandora_remote_media__',
      'variables' => array('object' => NULL),
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_remote_media_islandora_sp_remoteMediaCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_remote_media', array('object' => $object));
  return array('' => $output);
}
